version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - logisticsnet

  producer:
    build: ./producer-service
    container_name: producer
    ports:
      - "8001:8001"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbit:5672/
    depends_on:
      - rabbitmq
    networks:
      - logisticsnet

  consumer:
    build: ./consumer-service
    container_name: consumer
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbit:5672/
    depends_on:
      - rabbitmq
    networks:
      - logisticsnet

  monitor:
    build: ./monitor-service
    container_name: monitor
    ports:
      - "8002:8002"
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbit:5672/
      PRODUCER_URL: http://producer:8001
      QUEUE_NAME: shipment_updates
    depends_on:
      - rabbitmq
      - producer
    networks:
      - logisticsnet

networks:
  logisticsnet:
    driver: bridge
