apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-dashboard
  namespace: microservices-messaging
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
    - hosts:
        - monitor.local
      secretName: monitor-tls
  rules:
    - host: monitor.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monitor
                port:
                  number: 8002
